In [11]:
"""
Задание 1
Создайте двумерный массив размером 4×4, заполненный случайными целыми
числами от 1 до 50.
• Выведите массив в читаемом виде (в виде таблицы).
• Найдите сумму элементов по каждой строке и по каждому столбцу
(используйте параметр axis).
• Определите общее среднее значение массива.
• Выведите все результаты в удобном виде (например: «Суммы по строкам: …»,
«Суммы по столбцам: …»).
"""

import numpy as np

array = np.random.randint(1, 51, size=(4, 4))

print(array)

[[24 48  2 19]
 [13  5 19 44]
 [ 7 41 34 13]
 [25  5 45 45]]


In [8]:
# Суммы по строкам
row_sums = np.sum(array, axis=1)
print("Суммы по строкам:",row_sums)

Суммы по строкам: [ 77  75 113 103]


In [9]:
# Суммы по столбцам
col_sums = np.sum(array, axis=0)
print("Суммы по столбцам:",col_sums)

Суммы по столбцам: [ 94 101 133  40]


In [10]:
#общее среднее значение массива
average = np.mean(array)
print("Общее среднее значение массива:",average)

Общее среднее значение массива: 23.0


In [16]:
"""
Задание 2
Создайте массив размером 3×5, заполненный числами от 0 до 14.
• Выведите исходный массив.
• Выполните транспонирование массива (строки становятся столбцами, а
столбцы строками).
• Примените операцию reshape, чтобы получить массив 5×3.
• Отобразите результаты на экран.
"""

array_2 = np.arange(15).reshape((3, 5))
print("\nИсходный массив:\n",array_2)


Исходный массив:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [15]:
# Транспонирование массива
transposed_array = array_2.T
print("\nТранспонированный массив:\n",transposed_array)


Транспонированный массив:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [17]:
reshaped_array = array_2.reshape(5, 3)
print("\nМассив после reshape:\n",reshaped_array)


Массив после reshape:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [18]:
"""
Задание 3
Создайте Маrkdown-ячейку с заголовком "Отчёт по продажам" и подпишите: «В этом разделе мы считаем итоги по простым данным».
В кодовой ячейке создайте список продаж за неделю:
sales [120, 135, 100, 150, 90, 200, 170]
Посчитайте:
общее количество продаж за неделю;
среднее значение;
максимальное и минимальное значения.
Создайте Markdown-ячейку и оформите таблицу с результатами
"""

sales = [120, 135, 100, 150, 90, 200, 170]
total_sales = sum(sales)
average_sales = total_sales / len(sales)
max_sales = max(sales)
min_sales = min(sales)

print("Общая сумма:", total_sales)
print("Среднее значение:", average_sales)
print("Максимум:", max_sales)
print("Минимум:", min_sales)

Общая сумма: 965
Среднее значение: 137.85714285714286
Максимум: 200
Минимум: 90


| Показатель  | Значение |
|-------------|-----------|
| Общая сумма | 965 |
| Среднее     | 137.86 |
| Максимум    | 200 |
| Минимум     | 90 |